"""
setup_autostart.py — KingTrades One-Click Auto-Start Setup
=============================================================
Run this ONCE to configure the bot to start automatically when your PC boots.

Windows: Creates a Windows Task Scheduler task that runs watchdog.py
         at user logon — silently in the background.

Linux:   Creates a systemd user service (no root required).

Usage:
  python setup_autostart.py          # Install auto-start
  python setup_autostart.py remove   # Remove auto-start
  python setup_autostart.py status   # Check current status
  python setup_autostart.py test     # Run bot once to test (no restart loop)
"""

import os
import platform
import subprocess
import sys
from pathlib import Path

BOT_DIR  = Path(__file__).parent.resolve()
SYSTEM   = platform.system()

# Python interpreter inside the venv
VENV_PY = (
    BOT_DIR / "venv" / "Scripts" / "python.exe"
    if SYSTEM == "Windows"
    else BOT_DIR / "venv" / "bin" / "python"
)
PYTHON = str(VENV_PY) if VENV_PY.exists() else sys.executable

TASK_NAME = "KingTrades_NSE_Bot"
VBS_FILE  = BOT_DIR / "run_silent.vbs"


def banner(text: str) -> None:
    print(f"\n{'=' * 55}")
    print(f"  {text}")
    print('=' * 55)


# ─────────────────────────────────────────────────────────────────
# WINDOWS
# ─────────────────────────────────────────────────────────────────

def windows_create_vbs() -> None:
    """
    Create a VBScript launcher that runs watchdog.py with NO visible window.
    Double-clicking this starts the bot completely silently.
    """
    vbs = f'''
' KingTrades Silent Launcher — auto-generated by setup_autostart.py
' Runs the watchdog in the background with no console window.
Set WshShell = CreateObject("WScript.Shell")
WshShell.Run Chr(34) & "{PYTHON}" & Chr(34) & " " & Chr(34) & "{BOT_DIR / 'watchdog.py'}" & Chr(34), 0, False
Set WshShell = Nothing
'''.strip()
    VBS_FILE.write_text(vbs, encoding="utf-8")
    print(f"  Created: {VBS_FILE}")


def windows_install() -> None:
    banner("Installing Windows Auto-Start (Task Scheduler)")

    # Create the VBScript silent launcher
    windows_create_vbs()

    # Build schtasks command
    # Trigger: at logon of current user
    # Action: run the VBScript (which silently starts watchdog.py)
    # RunLevel: HighestAvailable = runs with normal user privileges
    cmd = [
        "schtasks", "/create", "/f",
        "/tn",  TASK_NAME,
        "/tr",  f'wscript.exe "{VBS_FILE}"',
        "/sc",  "ONLOGON",
        "/ru",  os.getenv("USERNAME", ""),
        "/rl",  "HIGHEST",
        "/it",                       # Only when user is logged in
    ]

    print(f"\n  Running: {' '.join(cmd)}\n")
    result = subprocess.run(cmd, capture_output=True, text=True)

    if result.returncode == 0:
        print("  SUCCESS: Task created in Windows Task Scheduler")
        print(f"\n  Task name : {TASK_NAME}")
        print(f"  Trigger   : At logon (auto-start when you log in to Windows)")
        print(f"  Action    : {VBS_FILE}")
        print(f"  Window    : Hidden (runs silently in background)")
        print(f"\n  The bot will now start AUTOMATICALLY every time you log in.")
        print(f"  To see it: open Task Manager → Details → look for python.exe")
    else:
        print(f"  ERROR: {result.stderr.strip()}")
        print("\n  FALLBACK: Adding to Startup folder instead...")
        windows_startup_folder_fallback()


def windows_startup_folder_fallback() -> None:
    """Add VBScript to Windows Startup folder as a fallback."""
    import winreg
    try:
        key = winreg.OpenKey(
            winreg.HKEY_CURRENT_USER,
            r"Software\Microsoft\Windows\CurrentVersion\Explorer\Shell Folders"
        )
        startup = winreg.QueryValueEx(key, "Startup")[0]
        winreg.CloseKey(key)
    except Exception:
        startup = Path.home() / "AppData" / "Roaming" / "Microsoft" / "Windows" / "Start Menu" / "Programs" / "Startup"

    import shutil
    dest = Path(startup) / "KingTrades_Bot.vbs"
    shutil.copy(VBS_FILE, dest)
    print(f"\n  Startup shortcut created: {dest}")
    print("  Bot will start silently when you log into Windows.")


def windows_remove() -> None:
    banner("Removing Windows Auto-Start")
    result = subprocess.run(
        ["schtasks", "/delete", "/f", "/tn", TASK_NAME],
        capture_output=True, text=True
    )
    if result.returncode == 0:
        print(f"  Removed Task Scheduler task: {TASK_NAME}")
    else:
        print(f"  Task not found or already removed: {result.stderr.strip()}")

    # Also clean up startup folder
    startup_vbs = (
        Path.home() / "AppData" / "Roaming" / "Microsoft"
        / "Windows" / "Start Menu" / "Programs" / "Startup"
        / "KingTrades_Bot.vbs"
    )
    if startup_vbs.exists():
        startup_vbs.unlink()
        print(f"  Removed startup shortcut: {startup_vbs}")

    if VBS_FILE.exists():
        VBS_FILE.unlink()
        print(f"  Removed: {VBS_FILE}")

    print("\n  Auto-start has been removed.")


def windows_status() -> None:
    banner("Windows Task Scheduler Status")
    result = subprocess.run(
        ["schtasks", "/query", "/tn", TASK_NAME, "/fo", "LIST"],
        capture_output=True, text=True
    )
    if result.returncode == 0:
        print(result.stdout)
    else:
        print(f"  Task '{TASK_NAME}' not found. Run: python setup_autostart.py")


# ─────────────────────────────────────────────────────────────────
# LINUX / MAC
# ─────────────────────────────────────────────────────────────────

def linux_install() -> None:
    banner(f"Installing Linux Auto-Start (systemd user service)")

    service_dir = Path.home() / ".config" / "systemd" / "user"
    service_dir.mkdir(parents=True, exist_ok=True)
    service_file = service_dir / "kingtrades.service"

    service_content = f"""[Unit]
Description=KingTrades NSE Momentum Bot
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
WorkingDirectory={BOT_DIR}
ExecStart={PYTHON} {BOT_DIR / "watchdog.py"}
Restart=always
RestartSec=60
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=default.target
"""
    service_file.write_text(service_content)
    print(f"  Created: {service_file}")

    cmds = [
        ["systemctl", "--user", "daemon-reload"],
        ["systemctl", "--user", "enable", "kingtrades"],
        ["systemctl", "--user", "start", "kingtrades"],
        ["loginctl",  "enable-linger", os.getenv("USER", "")],
    ]
    for cmd in cmds:
        result = subprocess.run(cmd, capture_output=True, text=True)
        status = "OK" if result.returncode == 0 else f"WARN: {result.stderr.strip()}"
        print(f"  {' '.join(cmd)} → {status}")

    print("\n  SUCCESS: systemd user service installed")
    print("  The bot will start automatically when your PC boots (even without login)")
    print("\n  Useful commands:")
    print("    systemctl --user status kingtrades   # Check status")
    print("    systemctl --user restart kingtrades  # Restart bot")
    print("    journalctl --user -u kingtrades -f   # Live logs")


def linux_remove() -> None:
    banner("Removing Linux Auto-Start")
    cmds = [
        ["systemctl", "--user", "stop",    "kingtrades"],
        ["systemctl", "--user", "disable", "kingtrades"],
    ]
    for cmd in cmds:
        subprocess.run(cmd, capture_output=True)
        print(f"  {' '.join(cmd)} → done")

    service_file = Path.home() / ".config" / "systemd" / "user" / "kingtrades.service"
    if service_file.exists():
        service_file.unlink()
        print(f"  Removed: {service_file}")

    subprocess.run(["systemctl", "--user", "daemon-reload"], capture_output=True)
    print("\n  Auto-start removed.")


def linux_status() -> None:
    banner("Linux Service Status")
    subprocess.run(["systemctl", "--user", "status", "kingtrades"])


# ─────────────────────────────────────────────────────────────────
# SHARED
# ─────────────────────────────────────────────────────────────────

def pre_checks() -> bool:
    """Verify everything is in place before setting up auto-start."""
    banner("Pre-flight Checks")
    ok = True

    checks = [
        (VENV_PY.exists(),       f"venv/{'Scripts' if SYSTEM=='Windows' else 'bin'}/python", "Run: python -m venv venv && pip install -r requirements.txt"),
        ((BOT_DIR / "main.py").exists(),     "main.py",     "Bot files missing — git clone the repo again"),
        ((BOT_DIR / "watchdog.py").exists(), "watchdog.py", "watchdog.py missing"),
        ((BOT_DIR / ".env").exists(),        ".env file",   "Copy .env.example to .env and fill in credentials"),
    ]

    for condition, label, fix in checks:
        status = "OK" if condition else "MISSING"
        icon   = "✅" if condition else "❌"
        print(f"  {icon} {label:<35} {status}")
        if not condition:
            print(f"       Fix: {fix}")
            ok = False

    # Check .env has required keys
    if (BOT_DIR / ".env").exists():
        env_text = (BOT_DIR / ".env").read_text()
        required = ["GROWW_EMAIL", "GROWW_TOTP_SECRET", "TELEGRAM_BOT_TOKEN"]
        for key in required:
            filled = key in env_text and f"{key}=" in env_text and \
                     env_text.split(f"{key}=")[1].split("\n")[0].strip() not in ("", "your_value_here")
            icon = "✅" if filled else "⚠️ "
            print(f"  {icon} .env: {key:<30} {'SET' if filled else 'NOT SET (fill in .env)'}")

    return ok


def test_run() -> None:
    """Run the bot once in test mode (no restart loop)."""
    banner("Test Run (single run, no auto-restart)")
    print(f"  Running: {PYTHON} watchdog.py --once")
    print("  Press Ctrl+C to stop\n")
    subprocess.run([PYTHON, str(BOT_DIR / "watchdog.py"), "--once"])


def main() -> None:
    action = sys.argv[1].lower() if len(sys.argv) > 1 else "install"

    if action == "install":
        if not pre_checks():
            print("\n⚠️  Fix the above issues before setting up auto-start.\n")
            return
        print()
        if SYSTEM == "Windows":
            windows_install()
        else:
            linux_install()
        print("\n" + "─" * 55)
        print("  SETUP COMPLETE")
        print("  The bot will now start automatically when your PC boots.")
        print("  No manual action needed on trading days.")
        print("─" * 55)

    elif action == "remove":
        if SYSTEM == "Windows":
            windows_remove()
        else:
            linux_remove()

    elif action == "status":
        pre_checks()
        if SYSTEM == "Windows":
            windows_status()
        else:
            linux_status()
        # Also show watchdog status
        status_file = BOT_DIR / "data" / "watchdog_status.json"
        if status_file.exists():
            import json
            s = json.loads(status_file.read_text())
            print("\nWatchdog last known state:")
            for k, v in s.items():
                print(f"  {k:<12}: {v}")

    elif action == "test":
        test_run()

    elif action == "uninstall":
        if SYSTEM == "Windows":
            windows_remove()
        else:
            linux_remove()

    else:
        print(__doc__)


if __name__ == "__main__":
    main()
